#!/usr/bin/env python3
"""SEO overhaul 2026-09-15 (staging): clean-URL canonicals, meta rewrites,
internal-link migration, footer links, noindex on utility pages, _redirects,
sitemap regeneration. Landing pages are generated by build_landing_20260915.py.

Idempotent-ish: safe to re-run only on a fresh prod-mirror tree; run once.
Every replacement asserts its expected match count so silent misses fail loud.
"""
import re, sys, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TODAY = "2026-09-15"
SITE = "https://immilane.com"

# page key -> (title, description). Only pages whose snippet we are rewriting.
META = {
    "index": (
        "PERM Status Check — Live DOL Case Tracker | ImmiLane",
        "Check your PERM status against live DOL data — 207,000+ labor certification cases updated daily, with estimates and email alerts when your case moves.",
    ),
    "estimate": (
        "PERM Estimate — Predict Your Approval Date | ImmiLane",
        "Estimate your PERM approval date from your filing date or case number, projected from the DOL's live processing pace. Free and updated daily.",
    ),
    "leaderboard": (
        "PERM Employer Leaderboard — Top Sponsors | ImmiLane",
        "U.S. employers ranked by PERM filing volume. Search any company to see green card sponsorship activity, certification rates, and top job titles.",
    ),
    "visa-bulletin": (
        "Visa Bulletin Tracker — EB Final Action Dates | ImmiLane",
        "Current Visa Bulletin final action dates and dates for filing for EB-1, EB-2, and EB-3 by country, with month-over-month movement tracking.",
    ),
    "about-perm": (
        "What Is PERM? Labor Certification Explained | ImmiLane",
        "The PERM labor certification process step by step: recruitment, ETA-9089 filing, DOL review, audits, and what happens after certification.",
    ),
    "faq": (
        "PERM FAQ — Processing Times, Audits and Status | ImmiLane",
        "Quick answers about PERM: how long it takes, how to check your case status, audits, certified vs analyst review, and what happens after approval.",
    ),
    "guides": (
        "PERM and Green Card Guides, Backed by DOL Data | ImmiLane",
        "Plain-English guides to PERM processing, EB-1/EB-2/EB-3 categories, audits and RFIs, the Visa Bulletin, and how PERM timelines are estimated.",
    ),
    "guide-how-dol-processes-perm": (
        "How the DOL Processes PERM Cases, in What Order | ImmiLane",
        "How the DOL works through PERM applications: strict filing-month order, why some months move faster, and where audited cases fit in the queue.",
    ),
    "guide-final-action-vs-filing-dates": (
        "Final Action Dates vs Dates for Filing, Explained | ImmiLane",
        "The two Visa Bulletin charts explained: Final Action Dates vs Dates for Filing, what your priority date is, and when you can file your I-485.",
    ),
    "guide-eb1-eb2-eb3-explained": (
        "EB-1 vs EB-2 vs EB-3: Differences and Timelines | ImmiLane",
        "EB-1, EB-2, and EB-3 employment green cards compared: who qualifies, which require PERM, NIW and downgrade options, and realistic timelines.",
    ),
    "guide-perm-audits-rfis": (
        "PERM Audits and RFIs — Triggers and Timelines | ImmiLane",
        "What triggers a PERM audit, what the DOL can request, how supervised recruitment works, and how much time audits add to your case.",
    ),
    "guide-estimate-methodology": (
        "How ImmiLane Predicts PERM Completion Dates | Methodology",
        "The methodology behind ImmiLane's PERM estimates: the DOL processing frontier, its measured pace, and how your projection is computed daily.",
    ),
    "about-us": (
        "About ImmiLane — Free PERM Tracker on Real DOL Data",
        "ImmiLane is an independent, free PERM tracker built on public DOL data — 207,000+ cases refreshed daily. Who runs it, and how the data works.",
    ),
    "support": (
        "Contact ImmiLane — PERM Tracker Support",
        "Get help with the ImmiLane PERM tracker, estimate tool, employer search, or Case Watch emails. Reach us at support@immilane.com.",
    ),
    "subscribe": (
        "Case Watch — PERM Status Change Email Alerts | ImmiLane",
        "Get an email when your PERM case status changes at the DOL, plus daily or weekly digests with your position in the queue and updated estimates.",
    ),
}

# every page that lives at a clean URL (for link migration + _redirects)
CLEAN_PAGES = [
    "about-perm", "about-us", "disclaimer", "employer", "estimate", "faq",
    "guide-eb1-eb2-eb3-explained", "guide-estimate-methodology",
    "guide-final-action-vs-filing-dates", "guide-how-dol-processes-perm",
    "guide-perm-audits-rfis", "guides", "leaderboard", "manage", "privacy",
    "refund", "subscribe", "support", "terms", "visa-bulletin",
]
NEW_PAGES = ["perm-status-check", "perm-case-status", "dol-case-status", "perm-processing-time"]

FOOTER_LINKS = ('<br><a href="perm-status-check">PERM Status Check</a> &middot; '
                '<a href="perm-case-status">Case Status Meanings</a> &middot; '
                '<a href="dol-case-status">DOL Case Status</a> &middot; '
                '<a href="perm-processing-time">Processing Times</a> &middot; ')

problems = []

def sub_expect(s, pat, repl, n, label, fname, flags=0):
    out, cnt = re.subn(pat, repl, s, flags=flags)
    if cnt != n:
        problems.append(f"{fname}: {label} matched {cnt}, expected {n}")
    return out

def esc(t):  # attribute/text-safe (we avoid quotes/& in copy anyway)
    return t.replace("&", "&amp;")

for path in sorted(ROOT.glob("*.html")):
    name = path.stem
    if name in NEW_PAGES:
        continue
    s = path.read_text(encoding="utf-8")
    orig = s

    # 1) canonical + og:url -> clean URL
    if name == "index":
        s = sub_expect(s, r'<meta property="og:url" content="https://immilane\.com">',
                       '<meta property="og:url" content="https://immilane.com/">', 1, "og:url", name)
    else:
        s = s.replace(f'<link rel="canonical" href="{SITE}/{name}.html">',
                      f'<link rel="canonical" href="{SITE}/{name}">')
        s = s.replace(f'<meta property="og:url" content="{SITE}/{name}.html">',
                      f'<meta property="og:url" content="{SITE}/{name}">')

    # 2) title/description/og/twitter rewrite
    if name in META:
        t, d = META[name]
        assert len(t) <= 60, (name, "title", len(t))
        assert len(d) <= 155, (name, "desc", len(d))
        s = sub_expect(s, r"<title>.*?</title>", f"<title>{esc(t)}</title>", 1, "title", name, re.S)
        s = sub_expect(s, r'(<meta name="description" content=")[^"]*(")',
                       rf"\g<1>{esc(d)}\g<2>", 1, "description", name)
        s = sub_expect(s, r'(<meta property="og:title" content=")[^"]*(")',
                       rf"\g<1>{esc(t)}\g<2>", 1, "og:title", name)
        s = sub_expect(s, r'(<meta property="og:description" content=")[^"]*(")',
                       rf"\g<1>{esc(d)}\g<2>", 1, "og:description", name)
        n_tw = 1 if 'name="twitter:title"' in s else 0
        if n_tw:
            s = sub_expect(s, r'(<meta name="twitter:title" content=")[^"]*(")',
                           rf"\g<1>{esc(t)}\g<2>", 1, "tw:title", name)
            s = sub_expect(s, r'(<meta name="twitter:description" content=")[^"]*(")',
                           rf"\g<1>{esc(d)}\g<2>", 1, "tw:description", name)

    # 3) internal link migration to clean URLs
    for p in CLEAN_PAGES:
        s = s.replace(f'href="{p}.html"', f'href="{p}"')
    s = s.replace('href="index.html"', 'href="./"')
    s = s.replace("'employer.html?e='", "'employer?e='")

    # 4) footer quick links (every page with the standard copyright)
    if "&copy; 2026 ImmiLane" in s and name not in ("manage", "visa-bulletin-mockup"):
        s = s.replace("&copy; 2026 ImmiLane", FOOTER_LINKS + "&copy; 2026 ImmiLane", 1)

    # 5) noindex for utility/mockup pages
    if name in ("manage", "visa-bulletin-mockup") and 'name="robots"' not in s:
        s = sub_expect(s, r'<meta charset="UTF-8">',
                       '<meta charset="UTF-8">\n<meta name="robots" content="noindex">',
                       1, "noindex insert", name)

    # 6) homepage extras: WebApplication description + in-content links to new pages
    if name == "index":
        s = sub_expect(
            s,
            r'"description": "Real-time PERM processing times tracker with DOL labor certification data, monthly backlogs, and processing analytics\."',
            '"description": "Check PERM status against live DOL data: 207,000+ labor certification cases, processing times, estimates, and email alerts."',
            1, "webapp ld description", name)
        anchor = ('<p>New to the process? Start with our plain-English '
                  '<a href="about-perm" style="color:#60a5fa;">overview of PERM</a>')
        if anchor not in s:
            problems.append("index: seo-content anchor paragraph not found")
        else:
            extra = ('  <p>Checking on your own case? See <a href="perm-status-check" style="color:#60a5fa;">how to check your PERM status</a>, '
                     '<a href="perm-case-status" style="color:#60a5fa;">what each case status means</a>, '
                     '<a href="perm-processing-time" style="color:#60a5fa;">current PERM processing times</a>, or '
                     '<a href="dol-case-status" style="color:#60a5fa;">how DOL case status works in FLAG</a>.</p>\n  ')
            s = s.replace(anchor, extra + anchor, 1)

    if s != orig:
        path.write_text(s, encoding="utf-8")
        print(f"updated {path.name}")

# 7) _redirects (Cloudflare Pages): explicit 301s .html -> clean
lines = ["# 301 .html -> clean URLs (canonical). CF Pages would otherwise 308 these.",
         "/index.html / 301"]
for p in CLEAN_PAGES + NEW_PAGES:
    lines.append(f"/{p}.html /{p} 301")
(ROOT / "_redirects").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote _redirects")

# 8) sitemap.xml: clean URLs, preserve per-URL changefreq/priority, add new pages
sm = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
entries = re.findall(r"<url>(.*?)</url>", sm, re.S)
out = ['<?xml version="1.0" encoding="UTF-8"?>',
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
seen = []
for e in entries:
    loc = re.search(r"<loc>(.*?)</loc>", e).group(1)
    cf = re.search(r"<changefreq>(.*?)</changefreq>", e).group(1)
    pr = re.search(r"<priority>(.*?)</priority>", e).group(1)
    clean = re.sub(r"\.html$", "", loc)
    seen.append(clean)
    out += ["  <url>", f"    <loc>{clean}</loc>", f"    <lastmod>{TODAY}</lastmod>",
            f"    <changefreq>{cf}</changefreq>", f"    <priority>{pr}</priority>", "  </url>"]
for p, cf, pr in [("perm-status-check", "daily", "0.9"), ("perm-case-status", "daily", "0.8"),
                  ("dol-case-status", "weekly", "0.8"), ("perm-processing-time", "daily", "0.9")]:
    out += ["  <url>", f"    <loc>{SITE}/{p}</loc>", f"    <lastmod>{TODAY}</lastmod>",
            f"    <changefreq>{cf}</changefreq>", f"    <priority>{pr}</priority>", "  </url>"]
out.append("</urlset>")
(ROOT / "sitemap.xml").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote sitemap.xml ({len(seen)} existing + 4 new URLs)")

if problems:
    print("\nPROBLEMS:")
    for p in problems:
        print(" -", p)
    sys.exit(1)
print("\nOK — all replacements matched expectations")
